### PR TITLE
improved mouse control

### PR DESCRIPTION
**Pull request by masa-sony**
modified mouse wheel control and right drag control.

### CODE REVIEW

**Comment by masa-sony** [comment]
I fixed the issue. Some changes were dropped during the commit.

**Comment by masa-sony** [comment]
I retrieved vertical translation control of the camera. Shift-right-drag to move the camera vertically.

**Comment by daisuke201** [comment]
## Changed the camera operation with mouse from merged this pull request.
- Right button drag: zooming to focus point that pointed right click
- Mouse wheel: zooming to mouse poiner (not changed)
- Shift + Right drag : Change altitude of camera

**Comment by daisuke201** [comment]
Thank you for modified and fixed some issue. this operation is very nice.

**Pull request merged**
